version: '3.7'

volumes:
    logs:
        driver: local

services:
    gasapp:
        build: .
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
            DATABASE: ${DATABASE}
            ENVIRONMENT: ${ENVIRONMENT}
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
            - .data.db:/var/data.db
